{
 "title": "TaskForge",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "legendFormat": "{{endpoint}}",
     "expr": "sum by (endpoint) (rate(app_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "p95",
     "expr": "histogram_quantile(0.95, sum by (le) (rate(app_http_request_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Error rate (5xx / total)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "legendFormat": "error rate",
     "expr": "sum(rate(app_http_errors_total[1m])) / sum(rate(app_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "sum(app_http_requests_total)" }
   ]
  }
 ]
}